### ISSUE TITLE
Fails with Rust config: error: '-exec' is not a valid command.

### ISSUE THREAD

**Issue by OctaveLarose** [jonboh/nvim-dap-rr#6]
This is likely to just be me making a silly mistake, but in case others encounter it I thought I'd ask.

On my Rust project, when attempting to use `nvim-dap-rr`, I can launch the program through the generated `rr` DAP config, but after my program segfaults (the reason why I'm debugging it!), I can't use rr operations successfully.

If I call `reverse-continue`:
```
[debug-adapter stderr] [ERROR codelldb::debug_session] error: '-exec' is not a valid command.
```

My config:
```lua

dap.adapters.rust = vim.g.rustaceanvim.dap.adapter 

dap.configurations.rust = {
  // ...
}

local rr_dap = require("nvim-dap-rr")
rr_dap.setup({
  mappings = {
     // ...
}
})

-- not sure if needed
local get_rust_gdb_path = function()
  local toolchain_location = string.gsub(vim.fn.system("rustc --print sysroot"), "\n", "")
  local rustgdb = toolchain_location .. "/bin/rust-gdb"
  return rustgdb
end

table.insert(dap.configurations.rust, rr_dap.get_rust_config(
  {
    name = "rr",
    type = "rust",
    program = function()
      vim.fn.system("cargo build --features=som-gc/stress_test");
      return vim.fn.getcwd() .. "/target/debug/som-interpreter-bc"
    end,
    args = function()
      return benchmark_args_fn()
    end,
    miDebuggerPath = get_rust_gdb_path,
    stopOnEntry = true
  }
))
```

I think it might not be using the right debugger, and is attempting a normal debug session as opposed to letting me go through the replay?

I was thinking that perhaps the `rustaceanvim` adapter might also be the cause and get in the way, not sure. If it is, that's a bit of a hassle, since I like using it for my usual debugging.

**Comment by jonboh** [comment]
Can you report your versions for codelldb, neovim, rustaceanvim etc? I can try to look into it, maybe there's been some change in codelldb that requires updating `nvim-dap-rr`.

Have you tried running it without overriding `dap.adapters.rust` with the rustaceanvim one? If it works at least it tells us that has something to do with settings on the adapter.

**Comment by OctaveLarose** [comment]
Sure thing:

```
$ nvim --version
NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
```

rustaceanvim: `5.15.3`

GDB (since I was using it in the example): `GNU gdb (Ubuntu 15.0.50.20240403-0ubuntu1) 15.0.50.20240403-git`

codelldb: `2024-11-28-lush-lilac`

I'd briefly tried no longer overriding the rust adapter with the rustaceanvim but then it wouldn't know where to find the Rust adapter for DAP. I'm not experienced enough to know what I could replace it with (other than copying https://github.com/mrcjkb/rustaceanvim/blob/b2df0caa67d41c63a7284b03e80aeff15d8e31ca/lua/rustaceanvim/config/init.lua#L279), and my understanding is that it just uses `codelldb`:

```lua
{
    'mrcjkb/rustaceanvim',
    version = '^5', 
    lazy = false,
    ft = "rust",
    config = function()
      local mason_registry = require('mason-registry')
      local codelldb = mason_registry.get_package("codelldb")
      local extension_path = codelldb:get_install_path() .. "/extension/"
      local codelldb_path = extension_path .. "adapter/codelldb"
      local liblldb_path = extension_path .. "lldb/lib/liblldb.so"

      vim.g.rustaceanvim = {
        dap = {
          adapter = cfg.get_codelldb_adapter(codelldb_path, liblldb_path),
        },
      // ...
}
```
...with `cfg.get_codelldb_adapter` being what I linked above.

Thanks for the fast response, btw. Really looking forward to using your plugin!

**Comment by jonboh** [comment]
Do you have `cpptools` installed? https://github.com/Microsoft/vscode-cpptools
Can you check using the adapter from that extension? Its been a while since I tweaked this part of my config I think the issue might be that the `-exec` part is exclusive of the cpptools extension and it isn't available on codelldb dap sessions. 
You can check my dap config here, if you want to start somewhere: https://github.com/jonboh/nixvim/blob/89d9e22e10202a9f6b6fbf20dafc9fdc03889543/config/dap.nix#L122
Or my old dotfiles, which although way more out of date should be more familiar of a typical nvim config:
https://github.com/jonboh/dotfiles/blob/2b824aca7d22b40ad68f95fc9fcdb3290073a220/.config/nvim/lua/jonbo/debugger/init.lua#L29

I think the problem in your config is that `nvim-dap-rr` is expecting a "cppdbg" type of dap adapter (one configured with its main binary being `OpenDebugAD7` from `cpptools`, instead of `codelldb`). Let me know if you find success this way, otherwise I'll put together a minimal nvim config to debug it.

**Comment by OctaveLarose** [comment]
I'd never used `cpptools` for Rust/dap before. It does fail by complaining about not being able to open `OpenDebugAD7`, which as it turns out has no executable bits. If granted executable permissions, it hangs for a while (`Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter...`) then starts but doesn't work.

I know that's technically unrelated to your package, but unless you know where I've gone wrong I'd prefer sticking with `codelldb` if possible... Installed them through `vscode` as recommended, btw.

**Comment by jonboh** [comment]
`cpptools` is a requirement for this plugin to work (https://github.com/jonboh/nvim-dap-rr?tab=readme-ov-file#installation).
If you use Mason, it is easier if you download `cpptools` through it. I've just tried with the kickstarter.nvim config and the package downloaded with Mason has OpenDebugAD7 and it is executable (`~/.local/share/nvim/mason/packages/cpptools/extension/debugAdapters/bin/OpenDebugAD7`). 
I've been able to run `nvim-dap-rr` as well on this config and it works as expected.

https://github.com/user-attachments/assets/13291337-fb9c-47fd-88dc-52d8f0473798


See this repo for for the config using kickstart.nvim: https://github.com/jonboh/kickstart-nvim-dap-rr
You have to download with Mason `cpptools`.

Are you sure you are running an rr session while running the debugger in neovim? The adapter might be timing out because it cannot connect to `127.0.0.1:50505`, which is the default address configured in the adapter.
You would usually record an execution with `rr record <executable>` and then serve that recording with `rr replay -s 50505 -k`. After that you should be able to connect with `nvim-dap-rr`.
I see that this isn't explicitly mentioned on the readme of the project, it is just shown on the gif and in the linked [post](https://jonboh.dev/posts/rr/), I'll add a note on the readme.
Let me know if you still cannot make it work with these instructions :)

**Comment by OctaveLarose** [comment]
Argh, of course, this was it: I wasn't starting the `rr` session myself, assuming the plugin was in charge of it! I thought that was the reason the executable was needed to be provided was for this purpose, though I assume it might be to get its debug info instead? Anyway, I knew this was an oversight on my part...

A quick test shows I can continue the session from neovim, so it does connect to it! It is struggling to find debug symbols, but then again I doubt I'm running it correctly (https://github.com/OctaveLarose/dotfiles/blob/5879446cebf9a83024f5f43df9f2f8d32058766f/config/nvim/after/ftplugin/rust.lua#L169). That's a case of me wrapping my head around DAP and not this plugin, I can fix this by myself.

And that config was very useful, thanks, I didn't know about `mason-nvim-dap`. Feel free to close this one, thanks for amending the README.

**Comment by jonboh** [comment]
No problem, glad I was able to help, and happy debugging! :D
